/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as ObjetivoIdRouteImport } from './routes/objetivo.$id'
import { Route as SubAgendaCategoriaRouteImport } from './routes/sub-agenda.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetivoIdRoute = ObjetivoIdRouteImport.update({
  id: '/objetivo/$id',
  path: '/objetivo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAgendaCategoriaRoute = SubAgendaCategoriaRouteImport.update({
  id: '/sub-agenda/$categoria',
  path: '/sub-agenda/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/planejamento': typeof PlanejamentoRoute
  '/objetivo/$id': typeof ObjetivoIdRoute
  '/sub-agenda/$categoria': typeof SubAgendaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/planejamento': typeof PlanejamentoRoute
  '/objetivo/$id': typeof ObjetivoIdRoute
  '/sub-agenda/$categoria': typeof SubAgendaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar': typeof CriarRoute
  '/dashboard': typeof DashboardRoute
  '/planejamento': typeof PlanejamentoRoute
  '/objetivo/$id': typeof ObjetivoIdRoute
  '/sub-agenda/$categoria': typeof SubAgendaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/criar'
    | '/dashboard'
    | '/planejamento'
    | '/objetivo/$id'
    | '/sub-agenda/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/criar'
    | '/dashboard'
    | '/planejamento'
    | '/objetivo/$id'
    | '/sub-agenda/$categoria'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/criar'
    | '/dashboard'
    | '/planejamento'
    | '/objetivo/$id'
    | '/sub-agenda/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CriarRoute: typeof CriarRoute
  DashboardRoute: typeof DashboardRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  ObjetivoIdRoute: typeof ObjetivoIdRoute
  SubAgendaCategoriaRoute: typeof SubAgendaCategoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetivo/$id': {
      id: '/objetivo/$id'
      path: '/objetivo/$id'
      fullPath: '/objetivo/$id'
      preLoaderRoute: typeof ObjetivoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-agenda/$categoria': {
      id: '/sub-agenda/$categoria'
      path: '/sub-agenda/$categoria'
      fullPath: '/sub-agenda/$categoria'
      preLoaderRoute: typeof SubAgendaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CriarRoute: CriarRoute,
  DashboardRoute: DashboardRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  ObjetivoIdRoute: ObjetivoIdRoute,
  SubAgendaCategoriaRoute: SubAgendaCategoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
